# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Support Repo"
  url = "docs/"
  weight = 2
[[main]]
    name = "Syllabus"  # A name for the link.
    url = "syllabus"  # URL of the section.
    weight = 1  # Position of the link in the menu.
[[main]]
    name = "Tutorials"  # A name for the link.
    url = "tutorials"  # URL of the section.
    weight = 3  # Position of the link in the menu.
[[main]]
    name = "Final assignment"  # A name for the link.
    url = "assignment"  # URL of the section.
    weight = 4  # Position of the link in the menu.
[[main]]
    name = "Credits/resources"  # A name for the link.
    url = "resources"  # URL of the section.
    weight = 6  # Position of the link in the menu.
[[main]]
    name = "About"  # A name for the link.
    url = "about"  # URL of the section.
    weight = 5  # Position of the link in the menu.
    
